test_with_go_modules: &test_with_go_modules
  steps:
    - checkout
    - run: go test ./...
    - run: go vet ./...

test_without_go_modules: &test_without_go_modules
  working_directory: /go/src/github.com/fairyhunter13/graphql
  steps:
    - checkout
    - run: go get -v -t -d ./...
    - run: go test ./...
    - run: go vet ./...

defaults: &defaults
  <<: *test_with_go_modules

version: 2
jobs:
  golang:latest:
    <<: *defaults
    docker:
      - image: circleci/golang:latest
  coveralls:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go get github.com/mattn/goveralls
      - run: go test -v -cover -race -coverprofile=coverage.out
      - run: /go/bin/goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - golang:latest
      - coveralls
